//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace At.FF.Krems.Config_Gui.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("At.FF.Krems.Config_Gui.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hinzufügen.
        /// </summary>
        public static string Add_DE_AT {
            get {
                return ResourceManager.GetString("Add_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element zu Liste hinzufügen..
        /// </summary>
        public static string Add_ToolTip_DE_AT {
            get {
                return ResourceManager.GetString("Add_ToolTip_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autostart.
        /// </summary>
        public static string Autostart_DE_AT {
            get {
                return ResourceManager.GetString("Autostart_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gibt an ob das Fenster beim Programmstart geöffnet werden soll..
        /// </summary>
        public static string Autostart_ToolTip_DE_AT {
            get {
                return ResourceManager.GetString("Autostart_ToolTip_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbrechen.
        /// </summary>
        public static string Cancel_DE_AT {
            get {
                return ResourceManager.GetString("Cancel_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cookies beim Start löschen.
        /// </summary>
        public static string ClearCookiesAtStartup_DE_AT {
            get {
                return ResourceManager.GetString("ClearCookiesAtStartup_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gibt an ob die gespeicherten Cookies bei jedem Programmstart gelöscht werden sollen.
        ///(Ist nur beim Testen sinnvoll.)
        ///ACHTUNG: Hierbei wird auch der Token gelöscht!.
        /// </summary>
        public static string ClearCookiesAtStartup_ToolTip_DE_AT {
            get {
                return ResourceManager.GetString("ClearCookiesAtStartup_ToolTip_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste aller definierten Cookies.
        ///Reihenfolge der Elemente ist egal..
        /// </summary>
        public static string CookieList_ToolTip_DE_AT {
            get {
                return ResourceManager.GetString("CookieList_ToolTip_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name des Cookies..
        /// </summary>
        public static string CookieName_ToolTip_DE_AT {
            get {
                return ResourceManager.GetString("CookieName_ToolTip_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screensaver dauerhaft deaktivieren.
        /// </summary>
        public static string DisableScreensaverPermanently_DE_AT {
            get {
                return ResourceManager.GetString("DisableScreensaverPermanently_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gibt an ob der Screensaver permanent deaktiviert werden soll..
        /// </summary>
        public static string DisableScreensaverPermanently_ToolTip_DE_AT {
            get {
                return ResourceManager.GetString("DisableScreensaverPermanently_ToolTip_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzeigename.
        /// </summary>
        public static string DisplayName_DE_AT {
            get {
                return ResourceManager.GetString("DisplayName_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzeigename des Tray-Icons..
        /// </summary>
        public static string DisplayName_ToolTip_DE_AT {
            get {
                return ResourceManager.GetString("DisplayName_ToolTip_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dauer.
        /// </summary>
        public static string Duration_DE_AT {
            get {
                return ResourceManager.GetString("Duration_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gibt an wie lange der Balken pro durchlauf benötigt um einmal über den gesamten Bildschirm zu scrollen..
        /// </summary>
        public static string Duration_ToolTip_DE_AT {
            get {
                return ResourceManager.GetString("Duration_ToolTip_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivieren.
        /// </summary>
        public static string Enable_DE_AT {
            get {
                return ResourceManager.GetString("Enable_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gibt an ob die Funktion zum refreshen der LCD-Pixel aktiviert ist..
        /// </summary>
        public static string Enable_ToolTip_DE_AT {
            get {
                return ResourceManager.GetString("Enable_ToolTip_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namen eintragen.
        /// </summary>
        public static string EnterName_DE_AT {
            get {
                return ResourceManager.GetString("EnterName_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ablaufdatum.
        /// </summary>
        public static string ExpirationDate_DE_AT {
            get {
                return ResourceManager.GetString("ExpirationDate_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum bis wann das Cookie gültig ist..
        /// </summary>
        public static string ExpirationDate_ToolTip_DE_AT {
            get {
                return ResourceManager.GetString("ExpirationDate_ToolTip_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;-- Vordergrund.
        /// </summary>
        public static string Front_DE_AT {
            get {
                return ResourceManager.GetString("Front_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allgemein.
        /// </summary>
        public static string General_DE_AT {
            get {
                return ResourceManager.GetString("General_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Höhe.
        /// </summary>
        public static string Height_DE_AT {
            get {
                return ResourceManager.GetString("Height_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to max für vollen Bildschirm oder eine beliebige Zahl für eine bestimmte Höhe des Fensters..
        /// </summary>
        public static string Height_ToolTip_DE_AT {
            get {
                return ResourceManager.GetString("Height_ToolTip_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        public static string Host_DE_AT {
            get {
                return ResourceManager.GetString("Host_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host bzw. Domain wofür das Cookie gültig ist..
        /// </summary>
        public static string Host_ToolTip_DE_AT {
            get {
                return ResourceManager.GetString("Host_ToolTip_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intervall.
        /// </summary>
        public static string Interval_DE_AT {
            get {
                return ResourceManager.GetString("Interval_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gibt die Zeitspanne zwischen zwei Durchgängen an..
        /// </summary>
        public static string Interval_ToolTip_DE_AT {
            get {
                return ResourceManager.GetString("Interval_ToolTip_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternatives Fenster.
        /// </summary>
        public static string IsAlternativeWindow_DE_AT {
            get {
                return ResourceManager.GetString("IsAlternativeWindow_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gibt an ob das Fenster dargestellt werden soll wenn kein Einsatz aktiv ist..
        /// </summary>
        public static string IsAlternativeWindow_ToolTip_DE_AT {
            get {
                return ResourceManager.GetString("IsAlternativeWindow_ToolTip_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nur HTTP.
        /// </summary>
        public static string IsHttpOnly_DE_AT {
            get {
                return ResourceManager.GetString("IsHttpOnly_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cookie wird nicht über Nicht-HTTP Verbindungen übertragen..
        /// </summary>
        public static string IsHttpOnly_ToolTip_DE_AT {
            get {
                return ResourceManager.GetString("IsHttpOnly_ToolTip_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sicher.
        /// </summary>
        public static string IsSecure_DE_AT {
            get {
                return ResourceManager.GetString("IsSecure_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cookie darf nur über eine sichere Verbindung (sprich HTTPS) zurückgeschickt werden..
        /// </summary>
        public static string IsSecure_ToolTip_DE_AT {
            get {
                return ResourceManager.GetString("IsSecure_ToolTip_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session.
        /// </summary>
        public static string IsSession_DE_AT {
            get {
                return ResourceManager.GetString("IsSession_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cookie ist nur für die aktuelle Sitzung gültig..
        /// </summary>
        public static string IsSession_ToolTip_DE_AT {
            get {
                return ResourceManager.GetString("IsSession_ToolTip_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kartentype.
        /// </summary>
        public static string MapType_DE_AT {
            get {
                return ResourceManager.GetString("MapType_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hydranten.
        /// </summary>
        public static string MaxHydrants_DE_AT {
            get {
                return ResourceManager.GetString("MaxHydrants_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximale Anzahl an Hydranten auf Druckseite.
        /// </summary>
        public static string MaxHydrants_ToolTip_DE_AT {
            get {
                return ResourceManager.GetString("MaxHydrants_ToolTip_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element nach unten verschieben..
        /// </summary>
        public static string MoveDown_ToolTip_DE_AT {
            get {
                return ResourceManager.GetString("MoveDown_ToolTip_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element nach oben verschieben..
        /// </summary>
        public static string MoveUp_ToolTip_DE_AT {
            get {
                return ResourceManager.GetString("MoveUp_ToolTip_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name_DE_AT {
            get {
                return ResourceManager.GetString("Name_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beliebiger Text - Gibt den Namen des Fensters im Tray-Icon an..
        /// </summary>
        public static string Name_ToolTip_DE_AT {
            get {
                return ResourceManager.GetString("Name_ToolTip_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nein.
        /// </summary>
        public static string No_DE_AT {
            get {
                return ResourceManager.GetString("No_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Über allen anderen Fenstern azeigen.
        /// </summary>
        public static string OnTop_DE_AT {
            get {
                return ResourceManager.GetString("OnTop_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gibt an ob das Fenster immer im Vordergrund sein soll..
        /// </summary>
        public static string OnTop_ToolTip_DE_AT {
            get {
                return ResourceManager.GetString("OnTop_ToolTip_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klick/Seitenanzahl.
        /// </summary>
        public static string PageNumberClick_DE_AT {
            get {
                return ResourceManager.GetString("PageNumberClick_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einsatz/Seitenanzahl.
        /// </summary>
        public static string PageNumberEmergency_DE_AT {
            get {
                return ResourceManager.GetString("PageNumberEmergency_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pfad.
        /// </summary>
        public static string Path_DE_AT {
            get {
                return ResourceManager.GetString("Path_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gültigkeit des Cookies auf einen bestimmten Pfad oder Pfadpräfix beschränken..
        /// </summary>
        public static string Path_ToolTip_DE_AT {
            get {
                return ResourceManager.GetString("Path_ToolTip_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string Port_DE_AT {
            get {
                return ResourceManager.GetString("Port_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port des Proxyservers.
        /// </summary>
        public static string Port_ToolTip_DE_AT {
            get {
                return ResourceManager.GetString("Port_ToolTip_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drucken.
        /// </summary>
        public static string Print_DE_AT {
            get {
                return ResourceManager.GetString("Print_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellung vom Infoscreen-Depeschen-Druckservice - nicht verändern!.
        /// </summary>
        public static string Print_ToolTip_DE_AT {
            get {
                return ResourceManager.GetString("Print_ToolTip_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bei Einsatz automatisch drucken.
        /// </summary>
        public static string PrintOnEmergency_DE_AT {
            get {
                return ResourceManager.GetString("PrintOnEmergency_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy.
        /// </summary>
        public static string Proxy_DE_AT {
            get {
                return ResourceManager.GetString("Proxy_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL auf eine Proxy-Config http://.../xyz.PAC.
        /// </summary>
        public static string ProxyUrl_ToolTip_DE_AT {
            get {
                return ResourceManager.GetString("ProxyUrl_ToolTip_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry.
        /// </summary>
        public static string Registry_DE_AT {
            get {
                return ResourceManager.GetString("Registry_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firefox Konfigurationen von about:config.
        /// </summary>
        public static string Registry_ToolTip_DE_AT {
            get {
                return ResourceManager.GetString("Registry_ToolTip_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neu laden.
        /// </summary>
        public static string Reload_DE_AT {
            get {
                return ResourceManager.GetString("Reload_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gibt die Zeitspanne an wann der Fensterinhalt komplett neu geladen werden soll.
        ///Bei 0 wird der Fensterinhalt nur zu Beginn geladen..
        /// </summary>
        public static string Reload_ToolTip_DE_AT {
            get {
                return ResourceManager.GetString("Reload_ToolTip_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Löschen.
        /// </summary>
        public static string Remove_DE_AT {
            get {
                return ResourceManager.GetString("Remove_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element von Liste entfernen..
        /// </summary>
        public static string Remove_ToolTip_DE_AT {
            get {
                return ResourceManager.GetString("Remove_ToolTip_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neustart.
        /// </summary>
        public static string Restart_DE_AT {
            get {
                return ResourceManager.GetString("Restart_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gibt die Zeitspanne  an wann das Fenster automatisch wieder gestartet werden soll, wenn es geschlossen wurde.
        ///Bei 0 wird es nicht automatisch neu gestartet..
        /// </summary>
        public static string Restart_ToolTip_DE_AT {
            get {
                return ResourceManager.GetString("Restart_ToolTip_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zurücksetzen.
        /// </summary>
        public static string Restore_DE_AT {
            get {
                return ResourceManager.GetString("Restore_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beim Start Ausführen.
        /// </summary>
        public static string RunAtStartup_DE_AT {
            get {
                return ResourceManager.GetString("RunAtStartup_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gibt an ob die Funktion beim Starten der Applikation ausgeführt werden soll..
        /// </summary>
        public static string RunAtStartup_ToolTip_DE_AT {
            get {
                return ResourceManager.GetString("RunAtStartup_ToolTip_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runtime.
        /// </summary>
        public static string Runtime_DE_AT {
            get {
                return ResourceManager.GetString("Runtime_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gibt den Pfad zur Applikation &quot;xulrunner&quot; an..
        /// </summary>
        public static string Runtime_ToolTip_DE_AT {
            get {
                return ResourceManager.GetString("Runtime_ToolTip_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern.
        /// </summary>
        public static string Save_DE_AT {
            get {
                return ResourceManager.GetString("Save_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Änderungen wurden noch nicht gespeichert!
        ///Wollen Sie jetzt speichern?.
        /// </summary>
        public static string SaveContent_DE_AT {
            get {
                return ResourceManager.GetString("SaveContent_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen Refresher.
        /// </summary>
        public static string ScreenRefresher_DE_AT {
            get {
                return ResourceManager.GetString("ScreenRefresher_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Screenrefresher ist ein Balken in verschiedenen Farben, in einer definierten Zeitspanne,
        ///quer über den Schirm läuft und so ein Einbrennen des Bildes verhindert..
        /// </summary>
        public static string ScreenRefresher_ToolTip_DE_AT {
            get {
                return ResourceManager.GetString("ScreenRefresher_ToolTip_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gibt die Höhe des Balkens an.
        ///-&gt; Desto Breiter, desto mehr wird die CPU belastet.
        ///-&gt; Besser den Wert von &quot;Dauer&quot; erhöhen..
        /// </summary>
        public static string ScreenRefresherHeight_ToolTip_DE_AT {
            get {
                return ResourceManager.GetString("ScreenRefresherHeight_ToolTip_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        public static string Server_DE_AT {
            get {
                return ResourceManager.GetString("Server_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP-Adresse oder Hostname des Proxyservers.
        /// </summary>
        public static string Server_ToolTip_DE_AT {
            get {
                return ResourceManager.GetString("Server_ToolTip_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bildschirm.
        /// </summary>
        public static string ShowOnScreen_DE_AT {
            get {
                return ResourceManager.GetString("ShowOnScreen_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gibt an auf welchem Schirm das Fenster gezeigt werden soll..
        /// </summary>
        public static string ShowOnScreen_ToolTip_DE_AT {
            get {
                return ResourceManager.GetString("ShowOnScreen_ToolTip_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon ToolsIcon {
            get {
                object obj = ResourceManager.GetObject("ToolsIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type_DE_AT {
            get {
                return ResourceManager.GetString("Type_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoProxy = kein Proxy
        ///Manual = manuell (Server und Port erforderlich)
        ///AutoConfigurationPac = automatisch (PAC, URL erforderlich)
        ///AutoDetect = automatisch erkennen
        ///SystemProxy = Systemproxy.
        /// </summary>
        public static string Type_ToolTip_DE_AT {
            get {
                return ResourceManager.GetString("Type_ToolTip_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url.
        /// </summary>
        public static string Url_DE_AT {
            get {
                return ResourceManager.GetString("Url_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eine beliebige URL - Adobe Flash auf der Webseite wird nicht unterstützt..
        /// </summary>
        public static string Url_ToolTip_DE_AT {
            get {
                return ResourceManager.GetString("Url_ToolTip_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wert.
        /// </summary>
        public static string Value_DE_AT {
            get {
                return ResourceManager.GetString("Value_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inhalt des Cookies..
        /// </summary>
        public static string Value_ToolTip_DE_AT {
            get {
                return ResourceManager.GetString("Value_ToolTip_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breite.
        /// </summary>
        public static string Width_DE_AT {
            get {
                return ResourceManager.GetString("Width_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to max für vollen Bildschirm, max2 für Vollbild über alle Bildschirme oder
        ///eine beliebige Zahl für eine bestimmte Breite des Fensters..
        /// </summary>
        public static string Width_ToolTip_DE_AT {
            get {
                return ResourceManager.GetString("Width_ToolTip_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fenstergröße.
        /// </summary>
        public static string WindowDimension_DE_AT {
            get {
                return ResourceManager.GetString("WindowDimension_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gibt die Größe des Fensters an..
        /// </summary>
        public static string WindowDimension_ToolTip_DE_AT {
            get {
                return ResourceManager.GetString("WindowDimension_ToolTip_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste aller definierten Fenster.
        ///Elemente können auch mittels Drag &amp; Drop verschoben werden..
        /// </summary>
        public static string WindowList_ToolTip_DE_AT {
            get {
                return ResourceManager.GetString("WindowList_ToolTip_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fensterposition.
        /// </summary>
        public static string WindowPosition_DE_AT {
            get {
                return ResourceManager.GetString("WindowPosition_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gibt an wo auf dem Schirm das Fenster gezeigt werden soll,
        ///es können damit auch mehrere Fenster auf einem Schirm angzeigt werden..
        /// </summary>
        public static string WindowPosition_ToolTip_DE_AT {
            get {
                return ResourceManager.GetString("WindowPosition_ToolTip_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        public static string X_DE_AT {
            get {
                return ResourceManager.GetString("X_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y.
        /// </summary>
        public static string Y_DE_AT {
            get {
                return ResourceManager.GetString("Y_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ja.
        /// </summary>
        public static string Yes_DE_AT {
            get {
                return ResourceManager.GetString("Yes_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom-Level.
        /// </summary>
        public static string ZoomLevel_DE_AT {
            get {
                return ResourceManager.GetString("ZoomLevel_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gibt die Zoomstufe des Browser-Textes an.
        ///0 und 1 ist 100% Ansicht.
        /// </summary>
        public static string ZoomLevel_ToolTip_DE_AT {
            get {
                return ResourceManager.GetString("ZoomLevel_ToolTip_DE_AT", resourceCulture);
            }
        }
    }
}
