//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace At.FF.Krems.FullscreenBrowser.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("At.FF.Krems.FullscreenBrowser.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache löschen.
        /// </summary>
        public static string clearCache_DE_AT {
            get {
                return ResourceManager.GetString("clearCache_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beenden.
        /// </summary>
        public static string Close_DE_AT {
            get {
                return ResourceManager.GetString("Close_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging.
        /// </summary>
        public static string logging_DE_AT {
            get {
                return ResourceManager.GetString("logging_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string ResetZoom_DE_AT {
            get {
                return ResourceManager.GetString("ResetZoom_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern.
        /// </summary>
        public static string Save_DE_AT {
            get {
                return ResourceManager.GetString("Save_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fenster schließen.
        /// </summary>
        public static string screenClose_DE_AT {
            get {
                return ResourceManager.GetString("screenClose_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bildschirm-Info.
        /// </summary>
        public static string screenInfo_DE_AT {
            get {
                return ResourceManager.GetString("screenInfo_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neu laden.
        /// </summary>
        public static string screenReload_DE_AT {
            get {
                return ResourceManager.GetString("screenReload_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starten.
        /// </summary>
        public static string screenStart_DE_AT {
            get {
                return ResourceManager.GetString("screenStart_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon TrayIcon {
            get {
                object obj = ResourceManager.GetObject("TrayIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        public static string Zoom_DE_AT {
            get {
                return ResourceManager.GetString("Zoom_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vergrößern.
        /// </summary>
        public static string ZoomIn_DE_AT {
            get {
                return ResourceManager.GetString("ZoomIn_DE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verkleinern.
        /// </summary>
        public static string ZoomOut_DE_AT {
            get {
                return ResourceManager.GetString("ZoomOut_DE_AT", resourceCulture);
            }
        }
    }
}
